Add `2.3.0-1-dev`
astronomer/ap-airflow pull request #464
Opened 2022-04-15 17:13 UTC by ephraimbuddy

Create `AC 2.3.0-1-dev`

2022-04-15 17:26 UTC, ashb approved these changes

2022-04-15 20:24 UTC, blag requested changes
Just a few nitpicks, otherwise looks good!

I differentiated the error messages for waiting for the database vs. waiting for the container, that should hopefully make it easier to troubleshoot if one of those isn't reachable.

2022-04-15 20:24 UTC, blag commented on 2.3.0/bullseye/include/entrypoint
> +  echo "Waiting for host: ${HOST} ${PORT}"
```suggestion
  # Wait for database port to open up
  [[ ${AIRFLOW__CORE__SQL_ALCHEMY_CONN} =~ $url_parse_regex ]]
  HOST=${BASH_REMATCH[2]}
  PORT=${BASH_REMATCH[3]}
  echo "Waiting for database: ${HOST}:${PORT}"
```

2022-04-15 20:24 UTC, blag commented on 2.3.0/bullseye/include/entrypoint
> +  echo "Waiting for host: ${HOST} ${PORT}"
```suggestion
  # Wait for broker port to open up
  [[ ${AIRFLOW__CELERY__BROKER_URL} =~ $url_parse_regex ]]
  HOST=${BASH_REMATCH[2]}
  PORT=${BASH_REMATCH[3]}
  echo "Waiting for broker: ${HOST}:${PORT}"
```

2022-04-15 20:24 UTC, blag commented on 2.3.0/bullseye/Dockerfile
> +    -e 's/^operation_timeout =.*/operation_timeout = 10.0/g' \
```suggestion
# Run pods spun up by Kubernetes Executor as astro user
# Lazily load all plugins, for astronomer-version-check-plugin
# Sync permissions in the entrypoint so we do not need to run in the Webserver again
# Use Astronomer FAB Security Manager authentication backend
# Configure a 10.0s timeout for send_task_to_executor or fetch_celery_task_state operations.
RUN sed -i \
    -e 's/^run_as_user =.*/run_as_user = 50000/g' \
    -e 's/^lazy_load_plugins =.*/lazy_load_plugins = False/g' \
    -e 's/^update_fab_perms =.*/update_fab_perms = False/g' \
    -e 's/^auth_backend =.*/auth_backend = astronomer.flask_appbuilder.current_user_backend/g' \
    -e 's/^operation_timeout =.*/operation_timeout = 10.0/g' \
```

See #463.

2022-04-15 20:25 UTC, ephraimbuddy commented
We need to create epoch providers. We don't have these ones in the constraints file

2022-04-18 04:34 UTC, jedcunningham approved these changes

2022-04-18 04:34 UTC, jedcunningham commented on 2.3.0/bullseye/build-time-pip-constraints.txt
> +apache-airflow-providers-cncf-kubernetes==1!3.1.2
```suggestion
apache-airflow-providers-cncf-kubernetes==1!4.0.0
```

2022-04-18 04:43 UTC, jedcunningham commented on 2.3.0/bullseye/Dockerfile
> +ARG ASTRONOMER_FAB_SECURITY_MANAGER_VERSION="1.8.4"
```suggestion
ARG ASTRONOMER_FAB_SECURITY_MANAGER_VERSION="1.9.0"
```

2022-04-18 04:43 UTC, jedcunningham commented on 2.3.0/bullseye/Dockerfile
> +ARG ASTRONOMER_FAB_SECURITY_MANAGER_VERSION="1.8.4"
```suggestion
ARG ASTRONOMER_FAB_SECURITY_MANAGER_VERSION="1.9.0"
```

2022-04-18 05:07 UTC, jedcunningham commented on 2.3.0/bullseye/Dockerfile
> +    -e 's/^auth_backend =.*/auth_backend = astronomer.flask_appbuilder.current_user_backend/g' \
```suggestion
    -e 's/^auth_backends =.*/auth_backends = astronomer.flask_appbuilder.current_user_backend/g' \
```

2022-04-18 05:26 UTC, merged